In [193]:
import pandas as pd
import numpy as np

# 01_Basic

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [194]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [195]:
chipo = pd.read_csv(url, sep="\t")

### Step 4. See the first 10 entries

In [196]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [197]:
chipo.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [198]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [199]:
list(chipo.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

### Step 8. How is the dataset indexed?

In [200]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [201]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [202]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 11. What was the most ordered item in the choice_description column?

In [203]:
chipo.groupby('choice_description')['quantity'].sum().sort_values(ascending=False).head(1)

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64

### Step 12. How many items were ordered in total?

In [204]:
chipo['quantity'].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

In [205]:
#chipo.item_price = chipo.item_price.str.replace("$", "").astype("float")

#### Step 13.a. Check the item price type

In [206]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

#### Step 13.b. Create a lambda function and change the type of item price

In [207]:
to_flo = lambda x: float(x)

chipo['item_price'] = chipo.item_price.str.replace("$", "").apply(to_flo)

#### Step 13.c. Check the item price type

In [208]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

### Step 14. How much was the revenue for the period in the dataset?

In [209]:
#Justificación de que la columna item_price contiene el precio completo del pedido, no hace falta multiplicar el precio por la cantidad:
chipo[["quantity", "choice_description", "item_price"]].loc[chipo.choice_description == "[Diet Coke]"].head(2)

     quantity choice_description  item_price
162         2        [Diet Coke]        2.18
200         1        [Diet Coke]        1.09

In [210]:
chipo['item_price'].sum()

np.float64(34500.16)

### Step 15. How many orders were made in the period?

In [211]:
chipo['order_id'].nunique()

1834

### Step 16. What is the average revenue amount per order?

In [212]:
chipo.groupby('order_id')['item_price'].sum().mean()

np.float64(18.811428571428568)

### Step 17. How many different items are sold?

In [213]:
chipo['item_name'].nunique()

50

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [214]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [215]:
users = pd.read_csv(url, sep="|", index_col="user_id")

### Step 4. See the first 25 entries

In [216]:
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [217]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [218]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [219]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [220]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [221]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [222]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

### Step 11. Print only the occupation column

In [223]:
users["occupation"]

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [224]:
users["occupation"].nunique()

21

### Step 13. What is the most frequent occupation?

In [225]:
users["occupation"].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [226]:
users.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 15. Summarize all the columns

In [227]:
users.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [228]:
users["occupation"].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [229]:
round(users["age"].mean(), 2)

np.float64(34.05)

### Step 18. What is the age with least occurrence?

In [230]:
#Podemos ver que hay un conjunto de edades que aparecen la misma cantidad de veces:
users["age"].value_counts()

age
30    39
25    38
22    37
28    36
27    35
      ..
7      1
66     1
11     1
10     1
73     1
Name: count, Length: 61, dtype: int64

In [231]:
frecuencias = users["age"].value_counts() #Al tenerlo aislado como una Serie puedo aplicar funciones sobre la misma, como min()

frecuencias.loc[ frecuencias == frecuencias.min() ]

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

# 02_Filtering & Sorting

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [232]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [233]:
chipo = pd.read_csv(url, sep="\t")

chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [234]:
#Para poder calcular lo que nos piden, primero debemos normalizar la columna "item_price":
chipo["item_price"] = chipo["item_price"].str.replace("$", "").astype("float")

In [235]:
#Que supone el precio de un producto? ##Supone el coste del pedido, entre la cantidad.
#Como puedo saber el precio unitario del pedido? ##Generando una columna nueva. 
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

chipo["item_name"].loc[ chipo["unit_price"] > 10].nunique()

25

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and item_price

In [236]:
chipo[["item_name", "choice_description", "unit_price"]].drop_duplicates()

,item_name,choice_description,unit_price
0,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
2,Nantucket Nectar,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.49
...,...,...,...
4602,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4607,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4610,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25

### Step 6. Sort by the name of the item

In [237]:
chipo.sort_values("item_name")

,order_id,quantity,item_name,choice_description,item_price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [238]:
chipo.loc[ chipo["unit_price"] == chipo["unit_price"].max() ][["item_name", "quantity"]]

                item_name  quantity
281      Steak Salad Bowl         2
606      Steak Salad Bowl         1
613      Steak Salad Bowl         2
749      Steak Salad Bowl         1
1132  Carnitas Salad Bowl         1
1159     Steak Salad Bowl         1
1229  Barbacoa Salad Bowl         1
1311     Steak Salad Bowl         1
1326  Barbacoa Salad Bowl         1
1505     Steak Salad Bowl         1
1571     Steak Salad Bowl         1
1590     Steak Salad Bowl         1
1816     Steak Salad Bowl         1
2401     Steak Salad Bowl         1
2439     Steak Salad Bowl         1
2442  Barbacoa Salad Bowl         1
2610  Carnitas Salad Bowl         1
2740     Steak Salad Bowl         1
2804     Steak Salad Bowl         1
2957     Steak Salad Bowl         1
3120     Steak Salad Bowl         1
3208  Barbacoa Salad Bowl         1
3350     Steak Salad Bowl         1
3493     Steak Salad Bowl         1
3546  Barbacoa Salad Bowl         1
3749  Carnitas Salad Bowl         1
4239  Carnitas Salad Bowl         1
4313     Steak Salad Bowl         1

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [239]:
chipo["item_name"].loc[ chipo["item_name"] == "Veggie Salad Bowl" ].value_counts()

item_name
Veggie Salad Bowl    18
Name: count, dtype: int64

### Step 9. How many times did someone order more than one Canned Soda?

In [240]:
chipo.loc[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)]["item_name"].count()

np.int64(20)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

In [241]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv"

### Step 3. Assign it to a variable called euro12.

In [242]:
euro12 = pd.read_csv(url)

euro12.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

### Step 4. Select only the Goal column.

In [243]:
euro12["Goals"]

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

### Step 5. How many team participated in the Euro2012?

In [244]:
euro12["Team"].nunique()

16

### Step 6. What is the number of columns in the dataset?

In [245]:
euro12.shape[1]

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [246]:
discipline = euro12[["Team", "Yellow Cards", "Red Cards"]]

discipline.head()

             Team  Yellow Cards  Red Cards
0         Croatia             9          0
1  Czech Republic             7          0
2         Denmark             4          0
3         England             5          0
4          France             6          0

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [247]:
discipline.sort_values(["Red Cards", "Yellow Cards"], ascending=False)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

### Step 9. Calculate the mean Yellow Cards given per Team

In [248]:
discipline["Yellow Cards"].mean()

np.float64(7.4375)

### Step 10. Filter teams that scored more than 6 goals

In [249]:
euro12.loc[ euro12["Goals"] > 6 ]["Team"]

5     Germany
13      Spain
Name: Team, dtype: object

### Step 11. Select the teams that start with G

In [250]:
euro12.loc[ euro12["Team"].str.startswith("G") ]["Team"]

5    Germany
6     Greece
Name: Team, dtype: object

### Step 12. Select the first 7 columns

In [251]:
column_names = list(euro12.columns)

euro12[column_names[:7]]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked)
0,Croatia,4,13,12,51.9%,16.0%,32
1,Czech Republic,4,13,18,41.9%,12.9%,39
2,Denmark,4,10,10,50.0%,20.0%,27
3,England,5,11,18,50.0%,17.2%,40
4,France,3,22,24,37.9%,6.5%,65
5,Germany,10,32,32,47.8%,15.6%,80
6,Greece,5,8,18,30.7%,19.2%,32
7,Italy,6,34,45,43.0%,7.5%,110
8,Netherlands,2,12,36,25.0%,4.1%,60
9,Poland,2,15,23,39.4%,5.2%,48
10,Portugal,6,22,42,34.3%,9.3%,82
11,Republic of Ireland,1,7,12,36.8%,5.2%,28
12,Russia,5,9,31,22.5%,12.5%,59
13,Spain,12,42,33,55.9%,16.0%,100
14,Sweden,5,17,19,47.2%,13.8%,39
15,Ukraine,2,7,26,21.2%,6.0%,38

### Step 13. Select all columns except the last 3.

In [252]:
euro12[column_names[:-3]]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,0,10,3,13,81.3%,41,62,2,9,0
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,1,10,6,9,60.1%,53,73,8,7,0
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,1,10,5,10,66.7%,25,38,8,4,0
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,2,29,3,22,88.1%,43,45,6,5,0
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,1,7,5,6,54.6%,36,51,5,6,0
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,1,11,6,10,62.6%,63,49,12,4,0
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,1,23,7,13,65.1%,67,48,12,9,1
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,2,18,7,20,74.1%,101,89,16,16,0
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,0,9,5,12,70.6%,35,30,3,5,0
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,0,8,3,6,66.7%,48,56,3,7,1
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,2,11,4,10,71.5%,73,90,10,12,0
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,0,23,9,17,65.4%,43,51,11,6,1
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,0,8,3,10,77.0%,34,43,4,6,0
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,5,8,1,15,93.8%,102,83,19,11,0
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,1,12,5,8,61.6%,35,51,7,7,0
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,0,4,4,13,76.5%,48,31,4,5,0

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [253]:
euro12.loc[ euro12["Team"].isin(["England", "Italy", "Russia"]) ][["Team", "Shooting Accuracy"]]

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%

### Step 2. This is the data given as a dictionary

In [254]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Step 3. Create a dataframe and assign it to a variable called army. 

#### Don't forget to include the columns names in the order presented in the dictionary ('regiment', 'company', 'deaths'...) so that the column index order is consistent with the solutions. If omitted, pandas will order the columns alphabetically.

In [255]:
army = pd.DataFrame(raw_data)

army.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine

### Step 4. Set the 'origin' colum as the index of the dataframe

In [256]:
army.set_index("origin", inplace=True) #Inplace=TRUE

army.head() #Solo para demostrar

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3

### Step 5. Print only the column veterans

In [257]:
army["veterans"].head()

origin
Arizona        1
California     5
Texas         62
Florida       26
Maine         73
Name: veterans, dtype: int64

### Step 6. Print the columns 'veterans' and 'deaths'

In [258]:
army[["veterans", "deaths"]].head()

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43

### Step 7. Print the name of all the columns.

In [259]:
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='object')

### Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [260]:
army.loc[ ["Maine", "Alaska"], ["deaths", "size", "deserters"] ]

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

### Step 9. Select the rows 3 to 7 and the columns 3 to 6

In [261]:
army.iloc[2:7, 2:6]

         deaths  battles  size  veterans
origin
Texas        25        2  1099        62
Florida     616        2  1400        26
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

### Step 10. Select every row after the fourth row and all columns

In [262]:
army.iloc[4:, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 11. Select every row up to the 4th row and all columns

In [263]:
army.iloc[:4, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2

### Step 12. Select the 3rd column up to the 7th column

In [264]:
army.iloc[:, 2:7]

            deaths  battles  size  veterans  readiness
origin
Arizona        523        5  1045         1          1
California      52       42   957         5          2
Texas           25        2  1099        62          3
Florida        616        2  1400        26          3
Maine           43        4  1592        73          2
Iowa           234        7  1006        37          1
Alaska         523        8   987       949          2
Washington      62        3   849        48          3
Oregon          62        4   973        48          2
Wyoming         73        7  1005       435          1
Louisana        37        8  1099        63          2
Georgia         35        9  1523       345          3

### Step 13. Select rows where df.deaths is greater than 50

In [265]:
army.loc[ army["deaths"] > 50 ]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

### Step 14. Select rows where df.deaths is greater than 500 or less than 50

In [266]:
army.loc[ (army["deaths"] > 500) | (army["deaths"] < 50)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 15. Select all the regiments not named "Dragoons"

In [267]:
army.loc[ army["regiment"] != "Dragoons" ]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 16. Select the rows called Texas and Arizona

In [268]:
army.loc[["Texas", "Arizona"]]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

### Step 17. Select the third cell in the row named Arizona

In [269]:
army.loc["Arizona", army.columns[2]]

np.int64(523)

### Step 18. Select the third cell down in the column named deaths

In [270]:
army["deaths"].iloc[2]

np.int64(25)

# 03_Grouping

### Step 2. Create the DataFrame with the following values:

In [271]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

### Step 3. Assign it to a variable called regiment.
#### Don't forget to name each column

In [272]:
regiment = pd.DataFrame(raw_data)

regiment.head()

     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
4    Dragoons     1st     Cooze             3             70

### Step 4. What is the mean preTestScore from the regiment Nighthawks?

In [273]:
regiment.loc[ regiment["regiment"] == "Nighthawks" ]["preTestScore"].mean()

np.float64(15.25)

### Step 5. Present general statistics by company

In [274]:
regiment.groupby(["company"]).describe()

        preTestScore                                                      \
               count       mean        std  min   25%   50%    75%   max
company
1st              6.0   6.666667   8.524475  2.0  3.00   3.5   4.00  24.0
2nd              6.0  15.500000  14.652645  2.0  2.25  13.5  29.25  31.0

        postTestScore
                count       mean        std   min    25%   50%   75%   max
company
1st               6.0  57.666667  27.485754  25.0  34.25  66.0  70.0  94.0
2nd               6.0  67.000000  14.057027  57.0  58.25  62.0  68.0  94.0

### Step 6. What is the mean of each company's preTestScore?

In [275]:
regiment.groupby(["company"])["preTestScore"].mean()

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

### Step 7. Present the mean preTestScores grouped by regiment and company

In [276]:
regiment.groupby(["regiment", "company"])["preTestScore"].mean()

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

### Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [277]:
regiment.groupby(["regiment", "company"], as_index=False)["preTestScore"].mean() #as_index=False

     regiment company  preTestScore
0    Dragoons     1st           3.5
1    Dragoons     2nd          27.5
2  Nighthawks     1st          14.0
3  Nighthawks     2nd          16.5
4      Scouts     1st           2.5
5      Scouts     2nd           2.5

### Step 9. Group the entire dataframe by regiment and company

In [278]:
[*regiment.groupby(["regiment", "company"])]

[(('Dragoons', '1st'),
     regiment company   name  preTestScore  postTestScore
  4  Dragoons     1st  Cooze             3             70
  5  Dragoons     1st  Jacon             4             25),
 (('Dragoons', '2nd'),
     regiment company    name  preTestScore  postTestScore
  6  Dragoons     2nd  Ryaner            24             94
  7  Dragoons     2nd    Sone            31             57),
 (('Nighthawks', '1st'),
       regiment company      name  preTestScore  postTestScore
  0  Nighthawks     1st    Miller             4             25
  1  Nighthawks     1st  Jacobson            24             94),
 (('Nighthawks', '2nd'),
       regiment company    name  preTestScore  postTestScore
  2  Nighthawks     2nd     Ali            31             57
  3  Nighthawks     2nd  Milner             2             62),
 (('Scouts', '1st'),
    regiment company   name  preTestScore  postTestScore
  8   Scouts     1st  Sloan             2             62
  9   Scouts     1st  Piger             3             70),
 (('Scouts', '2nd'),
     regiment company   name  preTestScore  postTestScore
  10   Scouts     2nd  Riani             2             62
  11   Scouts     2nd    Ali             3             70)]

### Step 10. What is the number of observations in each regiment and company

In [279]:
regiment.groupby(["regiment", "company"]).size()

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

### Step 11. Iterate over a group and print the name and the whole data from the regiment

In [280]:
for name, w_data in regiment.groupby(["regiment", "company"]):
    print(name)
    print(w_data)

('Dragoons', '1st')
   regiment company   name  preTestScore  postTestScore
4  Dragoons     1st  Cooze             3             70
5  Dragoons     1st  Jacon             4             25
('Dragoons', '2nd')
   regiment company    name  preTestScore  postTestScore
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
('Nighthawks', '1st')
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
('Nighthawks', '2nd')
     regiment company    name  preTestScore  postTestScore
2  Nighthawks     2nd     Ali            31             57
3  Nighthawks     2nd  Milner             2             62
('Scouts', '1st')
  regiment company   name  preTestScore  postTestScore
8   Scouts     1st  Sloan             2             62
9   Scouts     1st  Piger             3             70
('Scouts', '2nd')
   regiment company   name  preTestScore  postTestScore
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [281]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

### Step 3. Assign it to a variable called users.

In [282]:
users = pd.read_csv(url, sep="|")

users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [283]:
users.groupby(["occupation"])["age"].mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [284]:
#(users["gender"] == "M").groupby(users["occupation"]).mean().sort_values(ascending=False) ##Forma a tener en cuenta
users.replace({"M":1, "F":0}).groupby(["occupation"])["gender"].mean().sort_values(ascending=False)

/var/folders/2h/vps3xzys1vj_n4wcjx7rptp40000gn/T/ipykernel_25990/3934237770.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  users.replace({"M":1, "F":0}).groupby(["occupation"])["gender"].mean().sort_values(ascending=False)

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
Name: gender, dtype: float64

In [285]:
#Muestra de que los datos tomados en la celda anterior son correctos, dado que el ratio de mujeres doctoras es 0%
users.loc[ (users["gender"] == "F") & (users["occupation"] == "doctor") ]

Empty DataFrame
Columns: [user_id, age, gender, occupation, zip_code]
Index: []

### Step 6. For each occupation, calculate the minimum and maximum ages

In [286]:
users.groupby(["occupation"])["age"].agg(["min", "max"])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [287]:
users.groupby(["occupation", "gender"])["age"].mean()

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [288]:
users.groupby(['occupation', 'gender'])["gender"].size() / users["occupation"].value_counts()*100

occupation     gender
administrator  F          45.569620
               M          54.430380
artist         F          46.428571
               M          53.571429
doctor         M         100.000000
educator       F          27.368421
               M          72.631579
engineer       F           2.985075
               M          97.014925
entertainment  F          11.111111
               M          88.888889
executive      F           9.375000
               M          90.625000
healthcare     F          68.750000
               M          31.250000
homemaker      F          85.714286
               M          14.285714
lawyer         F          16.666667
               M          83.333333
librarian      F          56.862745
               M          43.137255
marketing      F          38.461538
               M          61.538462
none           F          44.444444
               M          55.555556
other          F          34.285714
               M          65.714286
programmer     F           9.090909
               M          90.909091
retired        F           7.142857
               M          92.857143
salesman       F          25.000000
               M          75.000000
scientist      F           9.677419
               M          90.322581
student        F          30.612245
               M          69.387755
technician     F           3.703704
               M          96.296296
writer         F          42.222222
               M          57.777778
dtype: float64

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [289]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv"

### Step 3. Assign it to a variable called drinks.

In [290]:
drinks = pd.read_csv(url, sep=",")

drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [291]:
#drinks.groupby("continent")["beer_servings"].mean().nlargest(1)
drinks.groupby("continent")["beer_servings"].mean().idxmax()

'EU'

### Step 5. For each continent print the statistics for wine consumption.

In [292]:
drinks.groupby("continent")["wine_servings"].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [293]:
drinks.groupby("continent")[["beer_servings", "spirit_servings", "wine_servings", "total_litres_of_pure_alcohol"]].mean()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

### Step 7. Print the median alcohol consumption per continent for every column

In [294]:
drinks.groupby("continent")[["beer_servings", "spirit_servings", "wine_servings", "total_litres_of_pure_alcohol"]].median()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption for each Continent.
#### This time output a DataFrame

In [295]:
drinks.groupby(["continent"])["spirit_servings"].agg(["mean", "min", "max"])

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302

# 04_Apply

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

In [296]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv"

### Step 3. Assign it to a variable called crime.

In [297]:
crime = pd.read_csv(url)

crime.head()

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

### Step 4. What is the type of the columns?

In [298]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     int64
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: int64(12)
memory usage: 5.3 KB

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [299]:
crime["Year"] = pd.to_datetime(crime["Year"], format="%Y")

crime.head()

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960-01-01,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961-01-01,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962-01-01,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963-01-01,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964-01-01,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

In [300]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     datetime64[ns]
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: datetime64[ns](1), int64(11)
memory usage: 5.3 KB

### Step 6. Set the Year column as the index of the dataframe

In [301]:
crime.set_index("Year", inplace=True)

crime.head()

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1960-01-01,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961-01-01,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962-01-01,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1963-01-01,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1964-01-01,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

### Step 7. Delete the Total column

In [302]:
crime.drop("Total", axis=1, inplace=True)

crime.head()

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,
1960-01-01,179323175,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961-01-01,182992000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962-01-01,185771000,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1963-01-01,188483000,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1964-01-01,191141000,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

In [303]:
decades_crimerate = crime.resample("10YS").agg({
    "Population" : "max",
    "Violent": "sum",
    "Property": "sum",
    "Murder": "sum",
    "Forcible_Rape": "sum",
    "Robbery": "sum",
    "Aggravated_assault": "sum",
    "Burglary": "sum",
    "Larceny_Theft": "sum",
    "Vehicle_Theft": "sum"
    })

### Step 9. What is the most dangerous decade to live in the US?

In [304]:
decades_crimerate[["Violent", "Property"]].sum(axis=1) / decades_crimerate["Population"]

Year
1960-01-01    0.244784
1970-01-01    0.458847
1980-01-01    0.528214
1990-01-01    0.500862
2000-01-01    0.374300
2010-01-01    0.157337
Freq: 10YS-JAN, dtype: float64

In [305]:
#La decada mas peligrosa significaria que hay la mayor cantidad de delitos por la menor proporcion de gente:
(decades_crimerate[["Violent", "Property"]].sum(axis=1) / decades_crimerate["Population"]).idxmax().year

1980

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

In [306]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv"

### Step 3. Assign it to a variable called df.

In [307]:
df = pd.read_csv(url)

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [308]:
df_slice = df.loc[:, "school":"guardian"]

df_slice.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father

### Step 5. Create a lambda function that will capitalize strings.

In [309]:
x_cap = lambda x: x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [310]:
df_slice[["Mjob", "Fjob"]].applymap(x_cap)

/var/folders/2h/vps3xzys1vj_n4wcjx7rptp40000gn/T/ipykernel_25990/2762022018.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_slice[["Mjob", "Fjob"]].applymap(x_cap)

         Mjob      Fjob
0     At_home   Teacher
1     At_home     Other
2     At_home     Other
3      Health  Services
4       Other     Other
..        ...       ...
390  Services  Services
391  Services  Services
392     Other     Other
393  Services     Other
394     Other   At_home

[395 rows x 2 columns]

### Step 7. Print the last elements of the data set.

In [311]:
df.iloc[-1:,:]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [312]:
df[["Mjob", "Fjob"]] = df[["Mjob", "Fjob"]].applymap(x_cap)

df.iloc[-1:,:]

/var/folders/2h/vps3xzys1vj_n4wcjx7rptp40000gn/T/ipykernel_25990/2830807117.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[["Mjob", "Fjob"]] = df[["Mjob", "Fjob"]].applymap(x_cap)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
394,MS,M,19,U,LE3,T,1,1,Other,At_home,...,3,2,3,3,3,5,5,8,9,9

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [313]:
#Mucho más facil y rapido, pero no soluciona el enunciado: df["legal_drinkers"] = df["age"] > 17

def majority(age):
    '''
    This function returns a boolean value as a confirmation of the user's age
    INPUT: int(age)
    OUTPUT: bool
    '''
    return age > 17


df["legal_drinkers"] = majority(df["age"])

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [314]:
#df.select_dtypes(include=['int', 'float']) * 10

n_cols = df.select_dtypes(include=['int', 'float']).columns

df[n_cols] = df[n_cols] * 10

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinkers
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,30,40,10,10,30,60,50,60,60,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,30,30,10,10,30,40,50,50,60,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,30,20,20,30,30,100,70,80,100,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,20,20,10,10,50,20,150,140,150,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,20,50,40,60,100,100,False

# 05_Merge

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

In [315]:
cars1_url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv"

cars2_url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv"

   ### Step 3. Assign each to a variable called cars1 and cars2

In [316]:
cars1 = pd.read_csv(cars1_url)

cars2 = pd.read_csv(cars2_url)

In [317]:
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [318]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [319]:
columns_2_del = cars1.loc[:, 'Unnamed: 9':].columns

cars1.drop(labels=columns_2_del, axis=1, inplace=True)

In [320]:
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [321]:
print(f"Observations Cars1: {cars1.shape[0]}")
print(f"Observations Cars2: {cars2.shape[0]}")

Observations Cars1: 198
Observations Cars2: 200

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [322]:
cars = pd.concat([cars1, cars2], ignore_index=True)

In [323]:
cars.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120,79,2625,18.6,82,1,ford ranger
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [324]:
#podemos hacerlo de la siguiente forma = np.random.randint(15000, 73000, 58000)

### Step 8. Add the column owners to cars

In [325]:
cars["owners"] = np.random.randint(15000, 73001, len(cars))

In [326]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,54738
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,50569
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,28353
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,40474
4,17.0,8,302,140,3449,10.5,70,1,ford torino,18887

### Step 2. Create the 3 DataFrames based on the following raw data

In [327]:
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

### Step 3. Assign each to a variable called data1, data2, data3

### Step 4. Join the two dataframes along rows and assign all_data

### Step 5. Join the two dataframes along columns and assing to all_data_col

### Step 6. Print data3

### Step 7. Merge all_data and data3 along the subject_id value

### Step 8. Merge only the data that has the same 'subject_id' on both data1 and data2

### Step 9. Merge all values in data1 and data2, with matching records from both sides where available.

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

### Step 3. Let's create a DataFrame by joinning the Series by column

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

### Step 6. Oops, it seems it is going only until index 99. Is it true?

### Step 7. Reindex the DataFrame so it goes from 0 to 299

# 06_Stats

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

### Step 4. See the first 10 entries

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

### Step 6. What year has the highest number of baby names in the dataset?

### Step 7. Is there more male or female names in the dataset?

### Step 8. Group the dataset by name and assign to names

### Step 9. How many different names exist in the dataset?

### Step 10. What is the name with most occurrences?

### Step 11. How many different names have the least occurrences?

### Step 12. What is the median name occurrence?

### Step 13. What is the standard deviation of names?

### Step 14. Get a summary with the mean, min, max, std and quartiles.