In [432]:
import pandas as pd
import numpy as np

# 01_Basic

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [433]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [434]:
chipo = pd.read_csv(url, sep="\t")

### Step 4. See the first 10 entries

In [435]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [436]:
chipo.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [437]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [438]:
list(chipo.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

### Step 8. How is the dataset indexed?

In [439]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [440]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [441]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 11. What was the most ordered item in the choice_description column?

In [442]:
chipo.groupby('choice_description')['quantity'].sum().sort_values(ascending=False).head(1)

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64

### Step 12. How many items were ordered in total?

In [443]:
chipo['quantity'].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

In [444]:
#chipo.item_price = chipo.item_price.str.replace("$", "").astype("float")

#### Step 13.a. Check the item price type

In [445]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

#### Step 13.b. Create a lambda function and change the type of item price

In [446]:
to_flo = lambda x: float(x)

chipo['item_price'] = chipo.item_price.str.replace("$", "").apply(to_flo)

#### Step 13.c. Check the item price type

In [447]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

### Step 14. How much was the revenue for the period in the dataset?

In [448]:
#Justificación de que la columna item_price contiene el precio completo del pedido, no hace falta multiplicar el precio por la cantidad:
chipo[["quantity", "choice_description", "item_price"]].loc[chipo.choice_description == "[Diet Coke]"].head(2)

     quantity choice_description  item_price
162         2        [Diet Coke]        2.18
200         1        [Diet Coke]        1.09

In [449]:
chipo['item_price'].sum()

np.float64(34500.16)

### Step 15. How many orders were made in the period?

In [450]:
chipo['order_id'].nunique()

1834

### Step 16. What is the average revenue amount per order?

In [451]:
chipo.groupby('order_id')['item_price'].sum().mean()

np.float64(18.811428571428568)

### Step 17. How many different items are sold?

In [452]:
chipo['item_name'].nunique()

50

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [453]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [454]:
users = pd.read_csv(url, sep="|", index_col="user_id")

### Step 4. See the first 25 entries

In [455]:
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [456]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [457]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [458]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [459]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [460]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [461]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

### Step 11. Print only the occupation column

In [462]:
users["occupation"]

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [463]:
users["occupation"].nunique()

21

### Step 13. What is the most frequent occupation?

In [464]:
users["occupation"].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [465]:
users.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 15. Summarize all the columns

In [466]:
users.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [467]:
users["occupation"].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [468]:
round(users["age"].mean(), 2)

np.float64(34.05)

### Step 18. What is the age with least occurrence?

In [469]:
#Podemos ver que hay un conjunto de edades que aparecen la misma cantidad de veces:
users["age"].value_counts()

age
30    39
25    38
22    37
28    36
27    35
      ..
7      1
66     1
11     1
10     1
73     1
Name: count, Length: 61, dtype: int64

In [470]:
frecuencias = users["age"].value_counts() #Al tenerlo aislado como una Serie puedo aplicar funciones sobre la misma, como min()

frecuencias.loc[ frecuencias == frecuencias.min() ]

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

# 02_Filtering & Sorting

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [471]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [472]:
chipo = pd.read_csv(url, sep="\t")

chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [473]:
#Para poder calcular lo que nos piden, primero debemos normalizar la columna "item_price":
chipo["item_price"] = chipo["item_price"].str.replace("$", "").astype("float")

In [483]:
#Que supone el precio de un producto? ##Supone el coste del pedido, entre la cantidad.
#Como puedo saber el precio unitario del pedido? ##Generando una columna nueva. 
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

chipo["item_name"].loc[ chipo["unit_price"] > 10].nunique()

25

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and item_price

In [487]:
chipo[["item_name", "choice_description", "unit_price"]].drop_duplicates()

,item_name,choice_description,unit_price
0,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
2,Nantucket Nectar,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.49
...,...,...,...
4602,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4607,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4610,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25

### Step 6. Sort by the name of the item

In [476]:
chipo.sort_values("item_name")

,order_id,quantity,item_name,choice_description,item_price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [485]:
chipo.loc[ chipo["unit_price"] == chipo["unit_price"].max() ][["item_name", "quantity"]]

                item_name  quantity
281      Steak Salad Bowl         2
606      Steak Salad Bowl         1
613      Steak Salad Bowl         2
749      Steak Salad Bowl         1
1132  Carnitas Salad Bowl         1
1159     Steak Salad Bowl         1
1229  Barbacoa Salad Bowl         1
1311     Steak Salad Bowl         1
1326  Barbacoa Salad Bowl         1
1505     Steak Salad Bowl         1
1571     Steak Salad Bowl         1
1590     Steak Salad Bowl         1
1816     Steak Salad Bowl         1
2401     Steak Salad Bowl         1
2439     Steak Salad Bowl         1
2442  Barbacoa Salad Bowl         1
2610  Carnitas Salad Bowl         1
2740     Steak Salad Bowl         1
2804     Steak Salad Bowl         1
2957     Steak Salad Bowl         1
3120     Steak Salad Bowl         1
3208  Barbacoa Salad Bowl         1
3350     Steak Salad Bowl         1
3493     Steak Salad Bowl         1
3546  Barbacoa Salad Bowl         1
3749  Carnitas Salad Bowl         1
4239  Carnitas Salad Bowl         1
4313     Steak Salad Bowl         1

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [484]:
chipo["item_name"].loc[ chipo["item_name"] == "Veggie Salad Bowl" ].value_counts()

item_name
Veggie Salad Bowl    18
Name: count, dtype: int64

### Step 9. How many times did someone order more than one Canned Soda?

In [479]:
chipo.loc[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)]["item_name"].count()

np.int64(20)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

### Step 3. Assign it to a variable called euro12.

### Step 4. Select only the Goal column.

### Step 5. How many team participated in the Euro2012?

### Step 6. What is the number of columns in the dataset?

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

### Step 9. Calculate the mean Yellow Cards given per Team

### Step 10. Filter teams that scored more than 6 goals

### Step 11. Select the teams that start with G

### Step 12. Select the first 7 columns

### Step 13. Select all columns except the last 3.

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

### Step 2. This is the data given as a dictionary

In [480]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Step 3. Create a dataframe and assign it to a variable called army. 

#### Don't forget to include the columns names in the order presented in the dictionary ('regiment', 'company', 'deaths'...) so that the column index order is consistent with the solutions. If omitted, pandas will order the columns alphabetically.

### Step 4. Set the 'origin' colum as the index of the dataframe

### Step 5. Print only the column veterans

### Step 6. Print the columns 'veterans' and 'deaths'

### Step 7. Print the name of all the columns.

### Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

### Step 9. Select the rows 3 to 7 and the columns 3 to 6

### Step 10. Select every row after the fourth row and all columns

### Step 11. Select every row up to the 4th row and all columns

### Step 12. Select the 3rd column up to the 7th column

### Step 13. Select rows where df.deaths is greater than 50

### Step 14. Select rows where df.deaths is greater than 500 or less than 50

### Step 15. Select all the regiments not named "Dragoons"

### Step 16. Select the rows called Texas and Arizona

### Step 17. Select the third cell in the row named Arizona

### Step 18. Select the third cell down in the column named deaths

# 03_Grouping

### Step 2. Create the DataFrame with the following values:

In [481]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

### Step 3. Assign it to a variable called regiment.
#### Don't forget to name each column

### Step 4. What is the mean preTestScore from the regiment Nighthawks?

### Step 5. Present general statistics by company

### Step 6. What is the mean of each company's preTestScore?

### Step 7. Present the mean preTestScores grouped by regiment and company

### Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing

### Step 9. Group the entire dataframe by regiment and company

### Step 10. What is the number of observations in each regiment and company

### Step 11. Iterate over a group and print the name and the whole data from the regiment

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

### Step 4. Discover what is the mean age per occupation

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

### Step 6. For each occupation, calculate the minimum and maximum ages

### Step 7. For each combination of occupation and gender, calculate the mean age

### Step 8.  For each occupation present the percentage of women and men

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

### Step 4. Which continent drinks more beer on average?

### Step 5. For each continent print the statistics for wine consumption.

### Step 6. Print the mean alcohol consumption per continent for every column

### Step 7. Print the median alcohol consumption per continent for every column

### Step 8. Print the mean, min and max values for spirit consumption for each Continent.
#### This time output a DataFrame

# 04_Apply

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.

### Step 4. What is the type of the columns?

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

### Step 6. Set the Year column as the index of the dataframe

### Step 7. Delete the Total column

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

### Step 9. What is the most dangerous decade to live in the US?

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

### Step 5. Create a lambda function that will capitalize strings.

### Step 6. Capitalize both Mjob and Fjob

### Step 7. Print the last elements of the data set.

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

# 05_Merge

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

### Step 5. What is the number of observations in each dataset?

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

### Step 8. Add the column owners to cars

### Step 2. Create the 3 DataFrames based on the following raw data

In [482]:
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

### Step 3. Assign each to a variable called data1, data2, data3

### Step 4. Join the two dataframes along rows and assign all_data

### Step 5. Join the two dataframes along columns and assing to all_data_col

### Step 6. Print data3

### Step 7. Merge all_data and data3 along the subject_id value

### Step 8. Merge only the data that has the same 'subject_id' on both data1 and data2

### Step 9. Merge all values in data1 and data2, with matching records from both sides where available.

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

### Step 3. Let's create a DataFrame by joinning the Series by column

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

### Step 6. Oops, it seems it is going only until index 99. Is it true?

### Step 7. Reindex the DataFrame so it goes from 0 to 299

# 06_Stats

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

### Step 4. See the first 10 entries

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

### Step 6. What year has the highest number of baby names in the dataset?

### Step 7. Is there more male or female names in the dataset?

### Step 8. Group the dataset by name and assign to names

### Step 9. How many different names exist in the dataset?

### Step 10. What is the name with most occurrences?

### Step 11. How many different names have the least occurrences?

### Step 12. What is the median name occurrence?

### Step 13. What is the standard deviation of names?

### Step 14. Get a summary with the mean, min, max, std and quartiles.