# Ex1 - Merge

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [83]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [84]:
url_cars1 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv'
url_cars2 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv'

cars1 = pd.read_csv(url_cars1)
cars2 = pd.read_csv(url_cars2)

cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [85]:
cars1.dropna(axis=1, inplace=True)

cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [86]:
print(f'Cars 1: {cars1.shape[0]} observations')
print(f'Cars 2: {cars2.shape[0]} observations')

Cars 1: 198 observations
Cars 2: 200 observations

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [87]:
cars = pd.concat([cars1, cars2], ignore_index=True)

print(f'Cars has {cars.shape[0]} observations')
print(f'Cars has {cars.shape[1]} columns')

cars.head()

Cars has 398 observations
Cars has 9 columns

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [88]:
random_owners = np.random.randint(15000, 73001, size=(cars.shape[0]))

### Step 8. Add the column owners to cars

In [89]:
cars['owners'] = random_owners

cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,69827
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,53444
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,44394
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,67809
4,17.0,8,302,140,3449,10.5,70,1,ford torino,50733